#include "../../../include/genericdefs/ssqc_api.qc"

void() main =
{
    dprint("Server: main loaded\n");
};

void() worldspawn =
{
    dprint("Server: worldspawn\n");
};

void() player_prethink =
{
};

void() player_postthink =
{
};

void() player_die =
{
};

void() SetNewParms =
{
};

void() SetChangeParms =
{
};

void() ResetPlayer =
{
};

void() StartFrame =
{
};

void() info_player_start =
{
};
